# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\SmartCar\Project\00_Software\00_HostPC\terminal.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(655, 434)
        Dialog.setSizeGripEnabled(True)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 221, 241))
        self.groupBox.setObjectName("groupBox")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 160, 61, 16))
        self.label_11.setObjectName("label_11")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(81, 21, 71, 126))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_2)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_3)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_5)
        self.comboBox_6 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_6)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(12, 23, 61, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(350, 10, 201, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_mv = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_mv.setGeometry(QtCore.QRect(91, 31, 71, 20))
        self.lineEdit_mv.setObjectName("lineEdit_mv")
        self.lineEdit_ma = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_ma.setGeometry(QtCore.QRect(91, 57, 71, 20))
        self.lineEdit_ma.setObjectName("lineEdit_ma")
        self.lineEdit_spd = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_spd.setGeometry(QtCore.QRect(91, 83, 71, 20))
        self.lineEdit_spd.setObjectName("lineEdit_spd")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(21, 31, 54, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(21, 56, 60, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(21, 81, 66, 16))
        self.label_6.setObjectName("label_6")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(350, 180, 271, 181))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(60, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 90, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 50, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 50, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(90, 120, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 54, 12))
        self.label_7.setObjectName("label_7")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_4.setGeometry(QtCore.QRect(110, 150, 69, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 160, 54, 12))
        self.label_8.setObjectName("label_8")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(84, 170, 81, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layoutWidget3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.layoutWidget4 = QtWidgets.QWidget(Dialog)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 260, 321, 151))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.pushButton_Reflesh = QtWidgets.QPushButton(Dialog)
        self.pushButton_Reflesh.setGeometry(QtCore.QRect(84, 210, 81, 31))
        self.pushButton_Reflesh.setObjectName("pushButton_Reflesh")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "智能车上位机"))
        self.groupBox.setTitle(_translate("Dialog", "settingGroupBox"))
        self.label_11.setText(_translate("Dialog", "关闭"))
        self.comboBox_2.setCurrentText(_translate("Dialog", "9600"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "9600"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "115200"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "4800"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "2400"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "1200"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "600"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "8"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "7"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "6"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "5"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "1.5"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "2"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "None"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "Odd"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "Even"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "Mark"))
        self.comboBox_6.setItemText(4, _translate("Dialog", "Space"))
        self.label.setText(_translate("Dialog", "串口号"))
        self.label_2.setText(_translate("Dialog", "波特率"))
        self.label_3.setText(_translate("Dialog", "数据位"))
        self.label_9.setText(_translate("Dialog", "停止位"))
        self.label_10.setText(_translate("Dialog", "校验位"))
        self.groupBox_2.setTitle(_translate("Dialog", "receiveGroupBox"))
        self.label_4.setText(_translate("Dialog", "电压值(mV)"))
        self.label_5.setText(_translate("Dialog", "电流值(mA)"))
        self.label_6.setText(_translate("Dialog", "车速(r/min)"))
        self.groupBox_3.setTitle(_translate("Dialog", "sendGroupBox"))
        self.pushButton.setText(_translate("Dialog", "forBtn"))
        self.pushButton_2.setText(_translate("Dialog", "backBtn"))
        self.pushButton_3.setText(_translate("Dialog", "leftBtn"))
        self.pushButton_4.setText(_translate("Dialog", "rightBtn"))
        self.label_7.setText(_translate("Dialog", "油门值："))
        self.comboBox_4.setItemText(0, _translate("Dialog", "N"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "D"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "R"))
        self.label_8.setText(_translate("Dialog", "档位值："))
        self.pushButton_5.setText(_translate("Dialog", "打开串口"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "编号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "方向"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "转速"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_Reflesh.setText(_translate("Dialog", "刷新串口"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

